platform: linux
image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.3.9-jdk-8

inputs:
- name: source-code

outputs:
- name: build-artifact

run:
  path: sh
  args:
    - -c
    - |
      echo "${M2_SETTINGS}" > ${HOME}/.m2/settings.xml
      echo "Calling Maven ..."
      cd source-code/mvn-pro
      mvn verify
      echo "Copying artifacts..."
      cp -r target/*.jar ../../build-artifact
      echo "0.0.1-SNAPSHOT" > ../../build-artifact/version_file