---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/octaviosg/test
    branch: master

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    target: source-code/workshop/task/build-and-verify.yml
