---
resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/octaviosg/test
    branch: master

jobs:
- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    file: source-code/workshop/tasks/build-and-verify.yml
    params:
        M2_SETTINGS: {{maven-settings-xml}}
